name: update-books

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r data/requirements.txt

    - name: Genera books.json
      run: python scripts/genera_books_json.py

    - name: Aggiungi link Anna's Archive
      run: python scripts/aggiungi_annas_archive.py

    - name: Scarica copertine
      run: python data/aggiungi_copertine.py

    - name: Copia JSON e copertine nella cartella /docs
      run: |
        mkdir -p docs/book_covers
        cp data/books.json docs/
        cp data/*.jpg docs/book_covers/ || echo "Nessuna immagine trovata"

    - name: Commit e push aggiornamenti
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add docs/books.json docs/book_covers/*.jpg || echo "Niente da aggiungere"
        git add data/books.json || echo "books.json già aggiornato"
        git commit -m "Aggiorna dati, copertine e date di uscita" || echo "Niente da commitare"
        git push
