name: Update Books Data

on:
  schedule:
    - cron: '0 4 * * *' # Ogni giorno alle 4:00 UTC
  workflow_dispatch:

jobs:
  update-books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run scraper script
        run: python scripts/update_books.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/books.json
          git commit -m "Update book list"
          git push

