name: Aggiorna Copertine Libri

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # ogni giorno alle 04:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clona la repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installa dipendenze
      run: pip install requests beautifulsoup4

    - name: Esegui script copertine
      run: python data/aggiungi_copertine.py

    - name: Lista immagini scaricate (debug)
      run: ls -l book_covers || echo "Nessuna cartella trovata"

    - name: Commit e Push aggiornamenti
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add book_covers/*.jpg || echo "Nessuna immagine trovata"
        git commit -m "Aggiornate copertine libri" || echo "Niente da commitare"
        git push
